services:
  postgres:
    image: postgres:16
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: svc
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  url-shortener:
    image: docker-url-shortener:latest
    container_name: url_shortener_server
    environment:
      US_PORT: 8080
    ports:
      - "8080:8080"
    depends_on: 
      - postgres

volumes:
  postgres_data:
